local_backend: true
publish_mode: editorial_workflow

backend:
  name: git-gateway
#  name: github
  squash_merges: true
  branch: content
  repo: mprokopov/mprokopov-blog-static

media_folder: "/static/img" # Folder where user uploaded files should go
public_folder: "/img"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    preview_path: posts/{{slug}}
    i18n: false
    # TODO: how to filter with no draft field set?
    # filter: {field: "draft", value: false}
    media_folder: "/static/img"
    public_folder: "/img"
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "content/posts" # The path to the folder where the documents are stored
    path: "{{slug}}"
    create: true 
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Draft", name: "draft", widget: "boolean", required: false}
      - {label: "Keywords", name: "keywords", widget: "list", allow_add: true}
      - {label: "Description", name: "description", widget: "text", required: false}

  - name: "drafts" 
    preview_path: posts/{{slug}}
    media_folder: "/static/img"
    public_folder: "/img"
    label: "Drafts" # Used in the UI, ie.: "New Post"
    filter: {field: "draft", value: true}
    folder: "content/posts" # The path to the folder where the documents are stored
    path: "{{slug}}"
    create: true 
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Draft", name: "draft", widget: "boolean", required: false}
      - {label: "Keywords", name: "keywords", widget: "list", allow_add: true}
      - {label: "Description", name: "description", widget: "text", required: false}
  - name: "pages" # Used in routes, ie.: /admin/collections/:slug/edit
    i18n: false
    media_folder: "/static/img"
    public_folder: "/img"
    label: "Page" # Used in the UI, ie.: "New Post"
    folder: "content/pages" # The path to the folder where the documents are stored
    # path: "{{slug}}"
    create: false 
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string", required: false}
      - {label: "Date", name: "date", widget: "datetime", format: "L", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Draft", name: "draft", widget: "boolean", required: false}
      - {label: "Keywords", name: "keywords", widget: "list", allow_add: true}
      - {label: "Description", name: "description", widget: "text", required: false}
